[package]
name = "game"
version = "0.1.0"
edition = "2021"

[dependencies]
macroquad = "0.3.13"
mongodb = "2.3.0"
bson = { version = "2", features = ["chrono-0_4"] } # Needed for using chrono datetime in doc
tokio = "1"
chrono = "0.4" # Used for setting DateTimes
serde = "1.0.152"
sqlx = {version = "0.5",features = [ "runtime-tokio-rustls", "migrate", "postgres" ]}